name: Jira Transition On Pull Request

on:
  pull_request:
    branches:
      - 'dev'

jobs:

  jira-transition:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Jira Transition
        run: |
          JIRA_ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oP 'DEV-\d+')
          echo "Jira Issue Key: $JIRA_ISSUE_KEY"

          JIRA_TRANSITION_URL="${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/${JIRA_ISSUE_KEY}/transitions"

          JIRA_TRANSITION_ID="pr-made"

          JIRA_API_USERNAME="${{ secrets.JIRA_USERNAME }}"
          JIRA_API_TOKEN="${{ secrets.JIRA_API_TOKEN }}"

          JIRA_TRANSITION_ID_RESPONSE=$(curl -u "$JIRA_API_USERNAME:$JIRA_API_TOKEN" -X GET -H "Content-Type: application/json" "$JIRA_TRANSITION_URL")
          echo "Jira Transition ID Response: $JIRA_TRANSITION_ID_RESPONSE"
          JIRA_TRANSITION_ID=$(echo "$JIRA_TRANSITION_ID_RESPONSE" | jq -r --arg name "pr-made" '.transitions[] | select(.name == $name) | .id')
          echo "Jira Transition ID: $JIRA_TRANSITION_ID"

          curl -X POST \
            --url "$JIRA_TRANSITION_URL" \
            --user "$JIRA_API_USERNAME:$JIRA_API_TOKEN" \
            --header "Content-Type: application/json" \
            --data '{"transition": {"id": "'"$JIRA_TRANSITION_ID"'"}}'
