name: Frontend Pull Request

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js and update Angular CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs
          sudo npm install -g @angular/cli@latest

      - name: Install Dependencies
        run: npm install

      - name: Build and Test
        run: npm run build --prod

      - name: SonarQube Scan
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=dev-ops-fmi_travelly-frontend \
            -Dsonar.organization=dev-ops-fmi \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN_ANGULAR: ${{ secrets.SONAR_TOKEN }}
